#include <bits/stdc++.h>
using namespace std;

int n = 3;                   // Size of our set {0, 1, 2}
vector<int> permutation;     // Holds the current permutation path
vector<bool> chosen;         // Tracks which elements are already in the permutation

void search() {
    // Base Case: If the permutation size matches 'n', we found a full permutation
    if (permutation.size() == n) {
        // Process permutation (printing it out as an example)
        cout << "[ ";
        for (auto x : permutation) {
            cout << x << " ";
        }
        cout << "]\n";
        return; 
    } 
    
    // Recursive Step: Try adding each unused element to the current position
    for (int i = 0; i < n; i++) {
        if (chosen[i]) continue; // Skip if the element is already used

        // 1. Make the choice
        chosen[i] = true;
        permutation.push_back(i);

        // 2. Move to the next position
        search();

        // 3. Backtrack (undo the choice for the next loop iteration)
        chosen[i] = false;
        permutation.pop_back();
    }
}

int main() {
    // Initialize the boolean tracking vector to be of size 'n' filled with 'false'
    chosen.resize(n, false);

    cout << "All permutations generated by recursion:\n";
    search();
    
    return 0;
}